### ISSUE TITLE
donation to Nebula-Contrib org

### ISSUE THREAD

**Issue by wey-gu** [mathlpz/graph-gateway#1]
@Shinji-IkariG could you please help @mathlpz with the repo transformation and membership(role grant)?

Thanks!

**Comment by mathlpz** [comment]
ok, thank you!

**Comment by wey-gu** [comment]
@mathlpz after you transfer the repo to @Shinji-IkariG , he will help transfer it to the nebula-contrib org then and grant you maintainer role there :)

**Comment by mathlpz** [comment]
ok

**Comment by wey-gu** [comment]
Thanks @mathlpz !
